[workspace]
members = [
    "fpp",
    "fpp_analysis",
    "fpp_ast",
    "fpp_core",
    "fpp_errors",
    "fpp_fs",
    "fpp_lexer",
    "fpp_lsp_server",
    "fpp_lsp_parser",
    "fpp_macros",
    "fpp_parser",
    "fpp_util",
    "fpp_format",
    "fpp_diagram",
]

# Exclude fpp_macros from test suite
default-members = [
    "fpp",
    "fpp_lsp_server",
    "fpp_analysis",
    "fpp_ast",
    "fpp_core",
    "fpp_errors",
    "fpp_lexer",
    "fpp_parser",
    "fpp_lsp_parser",
    "fpp_util",
    "fpp_diagram",
]

resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2024"
authors = ["Andrei Tumbar"]
license = "Apache-2.0"
repository = "https://github.com/fprime-community/fpp-tools"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
cargo = "warn"

[profile.release]
strip = "debuginfo"
lto = true
