//! Native PyO3 bindings to the Rust FPP compiler (`fpp-tools`).
//!
//! `analyze()` runs the full compiler pipeline in one `fpp_core::run` scope and
//! returns a [`model::Model`] backed by an owned [`ir_core::ModelData`]: the
//! *live* parsed AST, the *live* `fpp_analysis::Analysis`, and the *live*
//! `fpp_core::CompilerContext` — all kept alive for direct reads — plus small
//! `fpp_core::Node`-keyed side-tables (dense ids, type-tagged node pointers, a
//! span->node bridge) and the `by_qualified_name` index. There is no owned
//! per-node IR copy and no owned semantic mirror — wrappers read the live
//! `fpp_ast` nodes and the live `Analysis` directly.
//!
//! Design note: the fpp-tools compiler context is a non-reentrant `scoped_tls`
//! thread-local. Rather than pre-resolving every span/annotation into owned
//! tables, the context is retained in `ModelData` and re-entered lazily via
//! `fpp_core::run_ref` (a shared, read-only reflection scope) whenever a getter
//! needs a location, annotation, or `Connection`-keyed lookup.
//!
//! The recording walk and the AST wrapper layer are expanded at compile time by
//! `fpp_python_macros::fpp_ast_bindings!` from the `crate::ast` declaration
//! (`src/ast/defs.rs`, regenerated by
//! `cargo run -p fpp_python --features bindgen --bin fpp_bindgen`); only the
//! small core (`ir_core`, `lower_core`, `noderef`, `model`) is hand-written.

use pyo3::exceptions::PyRuntimeError;
use pyo3::prelude::*;
use pyo3_stub_gen::derive::gen_stub_pyfunction;
use std::panic::{AssertUnwindSafe, catch_unwind};

mod ast;
mod diagnostics;
mod entities_py;
mod enums;
mod ir_core;
mod lower_core;
mod model;
mod noderef;
mod sem_py;
mod unions;

use diagnostics::{Diagnostic, OwnedDiagnostic, SharedEmitter};
use model::Model;

/// Run the full pipeline on one in-memory source, collecting diagnostics.
/// Parse + analysis + the recording walk happen inside one `fpp_core::run`
/// scope (mirrors `fpp-tools/fpp/src/main.rs`). Unlike before, the compiler
/// context is **not** dropped when `run` returns: it is moved into the returned
/// [`ir_core::ModelData`] so locations/annotations resolve lazily via `run_ref`.
fn run_pipeline(uri: &str, content: String) -> (ir_core::ModelData, Vec<OwnedDiagnostic>) {
    let emitter = SharedEmitter::default();
    let mut ctx = fpp_core::CompilerContext::new(emitter.clone());
    #[allow(clippy::type_complexity)]
    let (tu, analysis, roots, ids, node_ptrs, nodes_by_span, by_qualified_name): (
        fpp_ast::TransUnit,
        fpp_analysis::Analysis,
        Vec<fpp_core::Node>,
        _,
        _,
        _,
        _,
    ) = fpp_core::run(&mut ctx, || {
        let src = fpp_core::SourceFile::new(uri, content);
        let mut ast = fpp_parser::parse(src, |p| p.trans_unit(), None);
        let mut analysis = fpp_analysis::Analysis::new();
        let _ = fpp_analysis::resolve_includes(&mut analysis, fpp_fs::FsReader {}, &mut ast);
        // Analyze an augmented *clone* so the compiler-synthesized per-state-
        // machine `enum State` never leaks into the exposed AST (which would make
        // state-machine sources non-idempotent on round-trip). The clone shares
        // node handles with `ast`, so analysis results key onto `ast`'s nodes;
        // the synthetic enum's fresh handles are absent from the walk and thus
        // skipped. `ast` itself is never mutated after this point, so the pointers
        // recorded by the walk stay valid (see `crate::noderef`).
        let mut augmented = ast.clone();
        fpp_analysis::add_state_enums(&mut augmented);
        let _ = fpp_analysis::check_semantics(&mut analysis, vec![&augmented]);
        let mut walker = lower_core::Walker::new();
        let roots = crate::ast::walk_trans_unit(&mut walker, &ast);
        let (ids, node_ptrs, nodes_by_span) = walker.finish();
        let by_qualified_name = lower_core::build_indexes(&analysis, &ids);
        (
            ast,
            analysis,
            roots,
            ids,
            node_ptrs,
            nodes_by_span,
            by_qualified_name,
        )
    });
    let data = ir_core::ModelData {
        tu,
        analysis,
        ctx: std::sync::Arc::new(ctx),
        roots,
        ids,
        node_ptrs,
        nodes_by_span,
        by_qualified_name,
    };
    (data, emitter.take())
}

/// Analyze FPP source text and return a [`Model`].
#[gen_stub_pyfunction]
#[pyfunction]
#[pyo3(signature = (source, uri = "<string>"))]
fn analyze(py: Python<'_>, source: String, uri: &str) -> PyResult<Py<Model>> {
    let uri = uri.to_owned();
    let (data, diags) = py
        .allow_threads(move || catch_unwind(AssertUnwindSafe(move || run_pipeline(&uri, source))))
        .map_err(|_| PyRuntimeError::new_err("internal FPP compiler panic"))?;
    Py::new(py, Model::new(data, diags))
}

#[pymodule]
fn fpp_python(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(analyze, m)?)?;
    m.add_class::<Model>()?;
    m.add_class::<Diagnostic>()?;
    m.add_class::<ir_core::Loc>()?;
    ast::register(m)?;
    sem_py::register(m)?;
    entities_py::register(m)?;
    enums::register(m)?;
    unions::register(m)?;
    Ok(())
}

/// Gather the pyo3-stub-gen [`StubInfo`] for this extension.
///
/// The inventory of `#[gen_stub_*]` submissions lives in this (`fpp_python`)
/// crate, so this gatherer must too. The `stub_gen` binary calls it to write the
/// stub. The output location is resolved from this crate's `pyproject.toml`
/// (`[tool.maturin] module-name`, pure-Rust layout), which sits beside
/// `Cargo.toml`: the stub is written as `fpp_python.pyi` and maturin ships it in
/// the wheel as `fpp_python/__init__.pyi`.
pub fn stub_info() -> pyo3_stub_gen::Result<pyo3_stub_gen::StubInfo> {
    let manifest_dir: &std::path::Path = env!("CARGO_MANIFEST_DIR").as_ref();
    pyo3_stub_gen::StubInfo::from_pyproject_toml(manifest_dir.join("pyproject.toml"))
}

/// `(alias name, `Sub1 | Sub2 | …` RHS)` for every closed-union type. Consumed by
/// the `stub_gen` binary to inject `<Alias>: typing.TypeAlias = …` lines that
/// pyo3-stub-gen cannot express natively.
pub fn union_aliases() -> Vec<(&'static str, String)> {
    unions::union_aliases()
}
