// @generated by fpp_sem_bindgen from fpp_analysis v0.0.0 — do not edit
//! Declarative mirror of the `fpp_analysis` semantic layer, expanded by the
//! `fpp_python_macros::fpp_sem_bindings!` proc macro into the read-only PyO3
//! wrappers for the semantic data structures. GENERATED by `fpp_sem_bindgen` —
//! do not edit by hand; regenerate with
//! `cargo run -p fpp_python --features bindgen --bin fpp_sem_bindgen`.
#![allow(dead_code, unused_variables, clippy::all)]

fpp_python_macros::fpp_sem_bindings! {
    union Type native fpp_analysis::semantics::Type handle arc_type alias "Type" accessor ty include_base custom_build {
        variants {
            PrimitiveInt => PrimitiveIntType : leaf(crate::ast::IntegerKind),
            Float => FloatType : leaf(crate::ast::FloatKind),
            String => StringType : opt(i128),
            Boolean => BooleanType : unit,
            Integer => IntegerType : unit,
            AbsType => AbsType : payload,
            AliasType => AliasType : payload,
            Array => ArrayType : payload,
            AnonArray => AnonArrayType : payload,
            Enum => EnumType : payload,
            Struct => StructType : payload,
            AnonStruct => AnonStructType : payload,
        }
        methods {
            assoc underlying_type -> type,
            default_value -> opt(value),
            array_size -> opt(usize),
            def_node_id -> opt(node),
            has_numeric_members -> bool,
            is_convertible_to_numeric -> bool,
            is_promotable_to_array -> bool,
            is_displayable -> bool,
            is_float -> bool,
            primitive_serialized_size -> opt(i128),
            serialized_size(analysis) -> opt(i128),
            is_int -> bool,
            is_primitive -> bool,
            is_canonical -> bool,
            is_promotable_to_struct -> bool,
            is_numeric -> bool,
        }
    }

    union Value native fpp_analysis::semantics::Value handle value alias "Value" accessor val {
        variants {
            PrimitiveInteger => PrimitiveIntegerValue : payload,
            AbsType => AbsTypeValue : payload,
            Integer => IntegerValue : newtype(i128),
            Float => FloatValue : payload,
            Boolean => BooleanValue : newtype(bool),
            String => StringValue : newtype(str),
            EnumConstant => EnumConstantValue : payload,
            AnonArray => AnonArrayValue : payload,
            Array => ArrayValue : payload,
            AnonStruct => AnonStructValue : payload,
            Struct => StructValue : payload,
        }
        methods {
            as_shift_int -> opt(i128),
            get_type -> type,
            is_zero -> bool,
            negate -> opt(value),
            truncate -> value,
        }
    }

    union Symbol native fpp_analysis::semantics::Symbol handle symbol alias "Symbol" accessor sym {
        variants {
            AbsType => AbsTypeSymbol : astdef(DefAbsType),
            AliasType => AliasTypeSymbol : astdef(DefAliasType),
            Array => ArraySymbol : astdef(DefArray),
            Component => ComponentSymbol : astdef(DefComponent),
            ComponentInstance => ComponentInstanceSymbol : astdef(DefComponentInstance),
            Constant => ConstantSymbol : astdef(DefConstant),
            Enum => EnumSymbol : astdef(DefEnum),
            EnumConstant => EnumConstantSymbol : astdef(DefEnumConstant),
            Interface => InterfaceSymbol : astdef(DefInterface),
            Module => ModuleSymbol : astdef(DefModule),
            Port => PortSymbol : astdef(DefPort),
            StateMachine => StateMachineSymbol : astdef(DefStateMachine),
            Struct => StructSymbol : astdef(DefStruct),
            System => SystemSymbol : astdef(DefSystem),
            Topology => TopologySymbol : astdef(DefTopology),
        }
        methods {
            is_dictionary_def -> bool,
        }
    }

    union StateMachineElement native fpp_analysis::semantics::state_machine::StateMachineSymbol handle clone alias "StateMachineElement" accessor native {
        variants {
            Action => SmAction : astdef(DefAction),
            Guard => SmGuard : astdef(DefGuard),
            Choice => SmChoice : astdef(DefChoice),
            Signal => SmSignal : astdef(DefSignal),
            State => SmState : astdef(DefState),
        }
    }

    payload AbsType native fpp_analysis::semantics::AbsType {
        fields {
            node: astdef(DefAbsType),
            default_value: opt(rewrap(Value::AbsType)),
        }
    }

    payload AbsTypeValue native fpp_analysis::semantics::AbsTypeValue {
        fields {
            ty: type,
        }
    }

    payload AliasType native fpp_analysis::semantics::AliasType {
        fields {
            node: astdef(DefAliasType),
            alias_type: type,
        }
    }

    payload AnonArrayType native fpp_analysis::semantics::AnonArrayType {
        fields {
            size: opt(usize),
            elt_type: type,
        }
    }

    payload AnonArrayValue native fpp_analysis::semantics::AnonArrayValue {
        fields {
            elements: list(value),
        }
    }

    payload AnonStructType native fpp_analysis::semantics::AnonStructType {
        fields {
            members: dict(type),
        }
    }

    payload AnonStructValue native fpp_analysis::semantics::AnonStructValue {
        fields {
            members: dict(value),
        }
    }

    payload ArrayType native fpp_analysis::semantics::ArrayType {
        fields {
            node: astdef(DefArray),
            anon_array: rewrap(Type::AnonArray),
            default: opt(value),
            format: skip,
        }
    }

    payload ArrayValue native fpp_analysis::semantics::ArrayValue {
        fields {
            anon_array: rewrap(Value::AnonArray),
            ty: type,
        }
    }

    payload EnumConstantValue native fpp_analysis::semantics::EnumConstantValue {
        fields {
            value: tuple(str, i128),
            ty: type,
        }
    }

    payload EnumType native fpp_analysis::semantics::EnumType {
        fields {
            node: astdef(DefEnum),
            rep_type: leaf(crate::ast::IntegerKind),
            default: opt(value),
        }
    }

    payload FloatValue native fpp_analysis::semantics::FloatValue {
        fields {
            value: f64,
            kind: leaf(crate::ast::FloatKind),
        }
    }

    payload PrimitiveIntegerValue native fpp_analysis::semantics::PrimitiveIntegerValue {
        fields {
            value: i128,
            kind: leaf(crate::ast::IntegerKind),
        }
    }

    payload StructType native fpp_analysis::semantics::StructType {
        fields {
            node: astdef(DefStruct),
            anon_struct: rewrap(Type::AnonStruct),
            default: opt(rewrap(Value::Struct)),
            sizes: dict(u32),
            formats: skip,
        }
    }

    payload StructValue native fpp_analysis::semantics::StructValue {
        fields {
            anon_struct: rewrap(Value::AnonStruct),
            ty: type,
        }
    }

}
