// @generated by fpp_sem_bindgen from fpp_analysis v0.0.0 — do not edit
//! Declarative mirror of the `fpp_analysis` semantic layer, expanded by the
//! `fpp_python_macros::fpp_sem_bindings!` proc macro into the read-only PyO3
//! wrappers for the semantic data structures. GENERATED by `fpp_sem_bindgen`
//! (rustdoc-JSON reflection of `fpp_analysis`, rooted at `Analysis`) — do not
//! edit by hand; regenerate with
//! `cargo run -p fpp_python --features bindgen --bin fpp_sem_bindgen`.
#![allow(dead_code, unused_variables, clippy::all)]

fpp_python_macros::fpp_sem_bindings! {
    analysis native fpp_analysis::Analysis {
        fields {
            parent_symbol_map: map(symbol, symbol),
            global_scope: entity(Scope),
            symbol_scope_map: map(symbol, entity(Scope)),
            symbol_map: map(node, symbol),
            use_def_map: map(node, symbol),
            use_def_matching_list: list(entity(UseDefMatching)),
            visited_symbol_set: list(symbol),
            use_def_symbol_set: list(symbol),
            parent_symbol: opt(symbol),
            nested_scope: entity(NestedScope),
            include_context_map: skip,
            type_map: map(node, type),
            value_map: map(node, value),
            framework_definitions: entity(FrameworkDefinitions),
            interface: opt(entity(Interface)),
            interface_map: map(symbol, entity(Interface)),
            component: opt(entity(Component)),
            component_map: map(symbol, entity(Component)),
            component_instance: opt(rewrap(InterfaceInstance::Component)),
            component_instance_map: map(symbol, rewrap(InterfaceInstance::Component)),
            topology: opt(entity(Topology)),
            partial_topology_map: map(symbol, entity(Topology)),
            topology_map: map(symbol, entity(Topology)),
            system_map: map(symbol, entity(FppSystem)),
            location_specifier_map: map(tuple(leaf(crate::ast::SpecLocKind), str), entity(SpecLocEntry)),
            scope_name_list: list(str),
            state_machine_map: map(symbol, entity(StateMachine)),
            dictionary_symbol_set: list(symbol),
            implied_use_map: map(node, entity(ImpliedUseSet)),
        }
        methods {
            get_qualified_name(symbol: symbol) -> str,
        }
    }

    union CommandKind native fpp_analysis::semantics::CommandKind handle clone alias "CommandKind" accessor native repr variant {
        variants {
            Async => Async : struct { priority: opt(i128), queue_full: leaf(crate::ast::QueueFull) },
            Guarded => Guarded : unit,
            Sync => Sync : unit,
        }
    }

    union FormatPart native fpp_analysis::semantics::FormatPart handle clone alias "FormatPart" accessor native repr variant {
        variants {
            Literal => Literal : str,
            FormatReplacement => FormatReplacementField : payload,
        }
    }

    union FormatReplacementKind native fpp_analysis::semantics::FormatReplacementKind handle clone alias "FormatReplacementKind" accessor native repr variant {
        variants {
            Default => FormatReplacementKindDefault : unit,
            Integer => FormatReplacementKindInteger : leaf(crate::sem::IntegerFormatKind),
            Rational => Rational : struct { precision: opt(usize), kind: leaf(crate::sem::RationalFormatKind) },
        }
    }

    union GeneralKind native fpp_analysis::semantics::GeneralKind handle clone alias "GeneralKind" accessor native repr variant {
        variants {
            AsyncInput => AsyncInput : struct { priority: opt(i128), queue_full: leaf(crate::ast::QueueFull) },
            GuardedInput => GuardedInput : unit,
            Output => Output : unit,
            SyncInput => SyncInput : unit,
        }
    }

    union InterfaceInstance native fpp_analysis::semantics::InterfaceInstance handle clone alias "InterfaceInstance" accessor native repr variant {
        variants {
            Component => InterfaceInstanceComponent : payload,
            Topology => TopologyInstance : payload,
        }
        methods {
            as_topology(a: analysis) -> opt(entity(Topology)),
            qualified_name -> str,
            unqualified_name -> str,
        }
    }

    union PortInstance native fpp_analysis::semantics::PortInstance handle clone alias "PortInstance" accessor native repr variant_unqualified {
        variants {
            General => General : struct { node_id: node, loc: span, name: str, kind: union(GeneralKind), size: i128, ty: union(PortInstanceType), import_locs: list(span) },
            Special => Special : struct { node_id: node, loc: span, name: str, kind: leaf(crate::ast::SpecialPortInstanceKind), input_kind: opt(leaf(crate::ast::InputPortKind)), symbol: symbol, priority: opt(i128), queue_full: opt(leaf(crate::ast::QueueFull)), import_locs: list(span) },
            Internal => PortInstanceInternal : struct { node_id: node, loc: span, name: str, priority: opt(i128), queue_full: leaf(crate::ast::QueueFull), import_locs: list(span) },
            Topology => PortInstanceTopology : struct { node_id: node, loc: span, name: str, underlying: port_instance },
        }
        methods {
            general_kind -> opt(union(GeneralKind)),
            get_array_size -> i128,
            get_direction -> opt(leaf(crate::sem::Direction)),
            get_node_id -> node,
            get_special_kind -> opt(leaf(crate::ast::SpecialPortInstanceKind)),
            get_type -> opt(union(PortInstanceType)),
            get_unqualified_name -> str,
            is_async_input -> bool,
            is_serial -> bool,
            priority -> opt(i128),
            queue_full -> opt(leaf(crate::ast::QueueFull)),
            type_symbol -> opt(symbol),
        }
    }

    union PortInstanceType native fpp_analysis::semantics::PortInstanceType handle clone alias "PortInstanceType" accessor native repr variant {
        variants {
            DefPort => DefPort : symbol,
            Serial => Serial : unit,
        }
        methods {
            port_returns_value -> opt(span),
        }
    }

    union StateMachineSymbol native fpp_analysis::semantics::state_machine::StateMachineSymbol handle clone alias "StateMachineSymbol" accessor native loc_from_node repr variant_unqualified {
        variants {
            Action => Action : astdef(DefAction),
            Guard => Guard : astdef(DefGuard),
            Choice => StateMachineSymbolChoice : astdef(DefChoice),
            Signal => Signal : astdef(DefSignal),
            State => StateMachineSymbolState : astdef(DefState),
        }
        methods {
            get_unqualified_name -> str,
            node -> node,
        }
    }

    union StateMachineTypedElement native fpp_analysis::semantics::state_machine::StateMachineTypedElement handle clone alias "StateMachineTypedElement" accessor native repr variant {
        variants {
            StateEntry => StateEntry : astdef(SpecStateEntry),
            StateExit => StateExit : astdef(SpecStateExit),
            InitialTransition => InitialTransition : astdef(SpecInitialTransition),
            StateTransition => StateTransition : astdef(SpecStateTransition),
            Choice => StateMachineTypedElementChoice : astdef(DefChoice),
        }
        methods {
            get_node_id -> node,
            show_kind -> str,
        }
    }

    union StateOrChoice native fpp_analysis::semantics::state_machine::StateOrChoice handle clone alias "StateOrChoice" accessor native repr variant {
        variants {
            State => StateOrChoiceState : union(StateMachineSymbol),
            Choice => StateOrChoiceChoice : union(StateMachineSymbol),
        }
        methods {
            get_name -> str,
            get_symbol -> union(StateMachineSymbol),
        }
    }

    union Symbol native fpp_analysis::semantics::Symbol handle symbol alias "Symbol" accessor sym identity node repr variant_qualified {
        variants {
            AbsType => SymbolAbsType : astdef(DefAbsType),
            AliasType => SymbolAliasType : astdef(DefAliasType),
            Array => Array : astdef(DefArray),
            Component => SymbolComponent : astdef(DefComponent),
            ComponentInstance => SymbolComponentInstance : astdef(DefComponentInstance),
            Constant => Constant : astdef(DefConstant),
            Enum => Enum : astdef(DefEnum),
            EnumConstant => EnumConstant : astdef(DefEnumConstant),
            Interface => SymbolInterface : astdef(DefInterface),
            Module => Module : astdef(DefModule),
            Port => Port : astdef(DefPort),
            StateMachine => SymbolStateMachine : astdef(DefStateMachine),
            Struct => Struct : astdef(DefStruct),
            System => System : astdef(DefSystem),
            Topology => SymbolTopology : astdef(DefTopology),
        }
        methods {
            is_dictionary_def -> bool,
            node -> node,
            parent(a: analysis) -> opt(symbol),
            qualified_name(a: analysis) -> str,
            unqualified_name -> str,
        }
    }

    union Transition native fpp_analysis::semantics::state_machine::Transition handle clone alias "Transition" accessor native repr variant {
        variants {
            External => External : struct { actions: list(union(StateMachineSymbol)), target: union(StateOrChoice) },
            Internal => TransitionInternal : struct { actions: list(union(StateMachineSymbol)) },
        }
        methods {
            get_target_opt -> opt(union(StateOrChoice)),
        }
    }

    union TransitionGraphArc native fpp_analysis::semantics::state_machine::transition_graph::Arc handle clone alias "TransitionGraphArc" accessor native repr variant {
        variants {
            Initial => Initial : struct { start_state: union(StateMachineSymbol), a_node: astdef(SpecInitialTransition), end_node: entity(TransitionGraphNode) },
            State => TransitionGraphArcState : struct { start_state: union(StateMachineSymbol), a_node: astdef(SpecStateTransition), end_node: entity(TransitionGraphNode) },
            Choice => TransitionGraphArcChoice : struct { start_choice: union(StateMachineSymbol), a_node: skip, end_node: entity(TransitionGraphNode) },
        }
        methods {
            get_end_node -> entity(TransitionGraphNode),
            get_start_node -> entity(TransitionGraphNode),
            get_typed_element -> union(StateMachineTypedElement),
            show_kind -> str,
            show_transition -> str,
        }
    }

    union Type native fpp_analysis::semantics::Type handle arc_type alias "Type" accessor ty include_base custom_build identity identical {
        variants {
            PrimitiveInt => PrimitiveInt : leaf(crate::ast::IntegerKind),
            Float => Float : leaf(crate::ast::FloatKind),
            String => TypeString : opt(i128),
            Boolean => TypeBoolean : unit,
            Integer => TypeInteger : unit,
            AbsType => TypeAbsType : payload,
            AliasType => TypeAliasType : payload,
            Array => ArrayType : payload,
            AnonArray => AnonArrayType : payload,
            Enum => EnumType : payload,
            Struct => StructType : payload,
            AnonStruct => AnonStructType : payload,
        }
        methods {
            array_size -> opt(usize),
            def_node_id -> opt(node),
            default_value -> opt(value),
            has_numeric_members -> bool,
            is_canonical -> bool,
            is_convertible_to_numeric -> bool,
            is_displayable -> bool,
            is_float -> bool,
            is_int -> bool,
            is_numeric -> bool,
            is_primitive -> bool,
            is_promotable_to_array -> bool,
            is_promotable_to_struct -> bool,
            primitive_serialized_size -> opt(i128),
            serialized_size(a: analysis) -> opt(i128),
            assoc underlying_type -> type,
        }
    }

    union Value native fpp_analysis::semantics::Value handle value alias "Value" accessor val repr variant {
        variants {
            PrimitiveInteger => PrimitiveIntegerValue : payload,
            AbsType => AbsTypeValue : payload,
            Integer => ValueInteger : newtype(i128),
            Float => FloatValue : payload,
            Boolean => ValueBoolean : newtype(bool),
            String => ValueString : newtype(str),
            EnumConstant => EnumConstantValue : payload,
            AnonArray => AnonArrayValue : payload,
            Array => ArrayValue : payload,
            AnonStruct => AnonStructValue : payload,
            Struct => StructValue : payload,
        }
        methods {
            as_shift_int -> opt(i128),
            get_type -> type,
            is_zero -> bool,
            negate -> opt(value),
            truncate -> value,
        }
    }

    payload AbsTypeValue native fpp_analysis::semantics::AbsTypeValue {
        fields {
            ty: type,
        }
    }

    payload AnonArrayType native fpp_analysis::semantics::AnonArrayType {
        fields {
            size: opt(usize),
            elt_type: type,
        }
    }

    payload AnonArrayValue native fpp_analysis::semantics::AnonArrayValue {
        fields {
            elements: list(value),
        }
    }

    payload AnonStructType native fpp_analysis::semantics::AnonStructType {
        fields {
            members: map(str, type),
        }
    }

    payload AnonStructValue native fpp_analysis::semantics::AnonStructValue {
        fields {
            members: map(str, value),
        }
    }

    payload ArrayType native fpp_analysis::semantics::ArrayType {
        fields {
            node: astdef(DefArray),
            anon_array: rewrap(Type::AnonArray),
            default: opt(value),
            format: opt(entity(Format)),
        }
    }

    payload ArrayValue native fpp_analysis::semantics::ArrayValue {
        fields {
            anon_array: rewrap(Value::AnonArray),
            ty: type,
        }
    }

    payload EnumConstantValue native fpp_analysis::semantics::EnumConstantValue {
        fields {
            value: tuple(str, i128),
            ty: type,
        }
    }

    payload EnumType native fpp_analysis::semantics::EnumType {
        fields {
            node: astdef(DefEnum),
            rep_type: leaf(crate::ast::IntegerKind),
            default: opt(value),
        }
    }

    payload FloatValue native fpp_analysis::semantics::FloatValue {
        fields {
            value: f64,
            kind: leaf(crate::ast::FloatKind),
        }
    }

    payload FormatReplacementField native fpp_analysis::semantics::FormatReplacementField {
        fields {
            span: span,
            kind: union(FormatReplacementKind),
        }
    }

    payload InterfaceInstanceComponent native fpp_analysis::semantics::ComponentInstance {
        fields {
            loc: span,
            name: str,
            qualified_name: str,
            base_id: i128,
            max_id: i128,
            queue_size: opt(i128),
            stack_size: opt(i128),
            priority: opt(i128),
            cpu: opt(i128),
            impl_type: opt(str),
            file: opt(str),
            init_specifier_map: map(i128, entity(InitSpecifier)),
            component_symbol: symbol,
        }
        methods {
            init_specifiers -> list(entity(InitSpecifier)),
        }
    }

    payload PrimitiveIntegerValue native fpp_analysis::semantics::PrimitiveIntegerValue {
        fields {
            value: i128,
            kind: leaf(crate::ast::IntegerKind),
        }
    }

    payload StructType native fpp_analysis::semantics::StructType {
        fields {
            node: astdef(DefStruct),
            anon_struct: rewrap(Type::AnonStruct),
            default: opt(rewrap(Value::Struct)),
            sizes: map(str, usize),
            formats: map(str, entity(Format)),
        }
    }

    payload StructValue native fpp_analysis::semantics::StructValue {
        fields {
            anon_struct: rewrap(Value::AnonStruct),
            ty: type,
        }
    }

    payload TopologyInstance native fpp_analysis::semantics::TopologyInstance {
        fields {
            symbol: symbol,
            qualified_name: str,
            loc: span,
        }
    }

    payload TypeAbsType native fpp_analysis::semantics::AbsType {
        fields {
            node: astdef(DefAbsType),
            default_value: opt(rewrap(Value::AbsType)),
        }
    }

    payload TypeAliasType native fpp_analysis::semantics::AliasType {
        fields {
            node: astdef(DefAliasType),
            alias_type: type,
        }
    }

    entity Command native fpp_analysis::semantics::Command {
        fields {
            loc: span,
            name: str,
            kind: opt(union(CommandKind)),
            opcode: i128,
        }
        methods {
            is_async -> bool,
        }
    }

    entity Component native fpp_analysis::semantics::Component {
        fields {
            symbol: symbol,
            node: astdef(DefComponent),
            loc: span,
            port_interface: entity(PortInterface),
            command_map: map(i128, entity(Command)),
            default_opcode: i128,
            tlm_channel_map: map(i128, entity(TlmChannel)),
            tlm_channel_name_map: map(str, entity(TlmChannel)),
            default_tlm_channel_id: i128,
            event_map: map(i128, entity(Event)),
            default_event_id: i128,
            param_map: map(i128, entity(Param)),
            default_param_id: i128,
            container_map: map(i128, entity(Container)),
            default_container_id: i128,
            record_map: map(i128, entity(Record)),
            default_record_id: i128,
            state_machine_instance_map: map(str, entity(StateMachineInstance)),
            spec_port_matching_list: list(astdef(SpecPortMatching)),
            port_matching_list: list(entity(PortMatching)),
        }
        methods {
            commands -> list(entity(Command)),
            containers -> list(entity(Container)),
            events -> list(entity(Event)),
            get_max_id -> i128,
            has_commands -> bool,
            has_data_products -> bool,
            has_events -> bool,
            has_parameters -> bool,
            has_telemetry -> bool,
            kind -> leaf(crate::ast::ComponentKind),
            params -> list(entity(Param)),
            records -> list(entity(Record)),
            tlm -> list(entity(TlmChannel)),
        }
    }

    entity Connection native fpp_analysis::semantics::Connection {
        fields {
            from: entity(Endpoint),
            to: entity(Endpoint),
            is_unmatched: bool,
        }
    }

    entity ConnectionPattern native fpp_analysis::semantics::ConnectionPattern {
        fields {
            loc: span,
            kind: leaf(crate::ast::ConnectionPatternKind),
            source: tuple(rewrap(InterfaceInstance::Component), span),
            targets: list(tuple(rewrap(InterfaceInstance::Component), span)),
        }
    }

    entity Container native fpp_analysis::semantics::Container {
        fields {
            loc: span,
            name: str,
            id: i128,
        }
    }

    entity Endpoint native fpp_analysis::semantics::Endpoint {
        fields {
            loc: span,
            port: entity(PortInstanceIdentifier),
            port_number: opt(i128),
            topology_port: opt(entity(Endpoint)),
        }
        methods {
            get_underlying_endpoint(a: analysis) -> entity(Endpoint),
        }
    }

    entity Event native fpp_analysis::semantics::Event {
        fields {
            loc: span,
            name: str,
            id: i128,
        }
    }

    entity Format native fpp_analysis::semantics::Format {
        methods {
            get(n: usize) -> opt(rewrap(FormatPart::FormatReplacement)),
            is_empty -> bool,
            len -> usize,
        }
    }

    entity FppSystem native fpp_analysis::semantics::FppSystem {
        fields {
            symbol: symbol,
            topology: symbol,
            loc: span,
        }
    }

    entity FrameworkDefinitions native fpp_analysis::semantics::FrameworkDefinitions {
        fields {
            constant_map: map(str, symbol),
            type_map: map(str, symbol),
        }
    }

    entity GuardedTransition native fpp_analysis::semantics::state_machine::GuardedTransition {
        fields {
            guard_opt: opt(union(StateMachineSymbol)),
            transition: union(Transition),
        }
    }

    entity ImpliedUse native fpp_analysis::semantics::ImpliedUse {
        methods {
            id -> node,
            name -> entity(QualifiedName),
        }
    }

    entity ImpliedUseSet native fpp_analysis::semantics::ImpliedUseSet {
        fields {
            constants: list(entity(ImpliedUse)),
            ports: list(entity(ImpliedUse)),
            types: list(entity(ImpliedUse)),
        }
    }

    entity InitSpecifier native fpp_analysis::semantics::InitSpecifier {
        fields {
            loc: span,
            phase: i128,
        }
    }

    entity Interface native fpp_analysis::semantics::Interface {
        fields {
            symbol: symbol,
            import_map: map(symbol, tuple(node, span)),
            port_interface: entity(PortInterface),
        }
    }

    entity NestedScope native fpp_analysis::semantics::NestedScope {
    }

    entity Param native fpp_analysis::semantics::Param {
        fields {
            loc: span,
            name: str,
            set_opcode: i128,
            save_opcode: i128,
            is_external: bool,
            id: i128,
        }
    }

    entity PendingTopPort native fpp_analysis::semantics::PendingTopPort {
        fields {
            name: str,
            node_id: node,
            loc: span,
            underlying_ast: skip,
        }
    }

    entity PortInstanceIdentifier native fpp_analysis::semantics::PortInstanceIdentifier identity qualified_name {
        fields {
            interface_instance: union(InterfaceInstance),
            port_instance: port_instance,
        }
        methods {
            qualified_name -> str,
        }
    }

    entity PortInterface native fpp_analysis::semantics::PortInterface {
        fields {
            instance_type: str,
            port_map: map(str, port_instance),
            special_port_map: map(str, port_instance),
        }
    }

    entity PortMatching native fpp_analysis::semantics::PortMatching {
        fields {
            instance1: port_instance,
            instance2: port_instance,
            loc: span,
        }
    }

    entity QualifiedName native fpp_analysis::semantics::QualifiedName {
        methods {
            to_ident_list -> list(str),
        }
    }

    entity Record native fpp_analysis::semantics::Record {
        fields {
            loc: span,
            name: str,
            id: i128,
        }
    }

    entity ResolvedConnection native fpp_analysis::semantics::ResolvedConnection {
        fields {
            from: entity(Endpoint),
            to: entity(Endpoint),
            is_unmatched: bool,
            graph_name: str,
            from_pn: opt(i128),
            to_pn: opt(i128),
        }
    }

    entity Scope native fpp_analysis::semantics::Scope {
    }

    entity SpecLocEntry native fpp_analysis::SpecLocEntry {
        fields {
            spec_span: span,
            file_span: span,
            file_value: str,
            is_dictionary_def: bool,
        }
    }

    entity StateMachine native fpp_analysis::semantics::state_machine::StateMachine {
        fields {
            node: astdef(DefStateMachine),
            sma: entity(StateMachineAnalysis),
            actions: list(union(StateMachineSymbol)),
            guards: list(union(StateMachineSymbol)),
            signals: list(union(StateMachineSymbol)),
        }
        methods {
            blocking_error -> bool,
            get_kind -> leaf(crate::sem::Kind),
            get_symbol -> symbol,
            has_actions -> bool,
            has_guards -> bool,
            has_signals -> bool,
            leaf_state_names -> list(str),
        }
    }

    entity StateMachineAnalysis native fpp_analysis::semantics::state_machine::StateMachineAnalysis {
        fields {
            symbol: symbol,
            scope_name_list: list(str),
            nested_scope: entity(StateMachineNestedScope),
            parent_state: opt(union(StateMachineSymbol)),
            parent_state_map: map(union(StateMachineSymbol), union(StateMachineSymbol)),
            symbol_scope_map: map(union(StateMachineSymbol), entity(StateMachineScope)),
            use_def_map: map(node, union(StateMachineSymbol)),
            transition_graph: entity(TransitionGraph),
            reverse_transition_graph: entity(TransitionGraph),
            type_option_map: map(union(StateMachineTypedElement), opt(type)),
            signal_transition_map: map(union(StateMachineSymbol), entity(GuardedTransition)),
            flattened_state_transition_map: map(union(StateMachineSymbol), map(union(StateMachineSymbol), entity(GuardedTransition))),
            flattened_choice_transition_map: map(node, union(Transition)),
            blocking_error: bool,
        }
    }

    entity StateMachineInstance native fpp_analysis::semantics::StateMachineInstance {
        fields {
            loc: span,
            name: str,
            symbol: symbol,
        }
    }

    entity StateMachineNestedScope native fpp_analysis::semantics::state_machine::StateMachineNestedScope {
        methods {
            inner_scope -> entity(StateMachineScope),
        }
    }

    entity StateMachineScope native fpp_analysis::semantics::state_machine::StateMachineScope {
    }

    entity TlmChannel native fpp_analysis::semantics::TlmChannel {
        fields {
            loc: span,
            name: str,
            id: i128,
        }
    }

    entity Topology native fpp_analysis::semantics::Topology {
        fields {
            symbol: symbol,
            name: str,
            loc: span,
            implements: skip,
            direct_component_instances: map(symbol, span),
            direct_topologies: map(symbol, span),
            transitive_import_set: list(symbol),
            instance_map: map(union(InterfaceInstance), span),
            ports: list(entity(PendingTopPort)),
            raw_direct_graphs: list(astdef(SpecDirectConnectionGraph)),
            raw_patterns: list(astdef(SpecPatternConnectionGraph)),
            port_map: map(str, entity(TopologyPort)),
            port_interface: entity(PortInterface),
            pattern_map: map(leaf(crate::ast::ConnectionPatternKind), entity(ConnectionPattern)),
            connection_map: map(str, list(entity(Connection))),
            local_connection_map: map(str, list(entity(Connection))),
            output_connection_map: map(entity(PortInstanceIdentifier), list(entity(Connection))),
            input_connection_map: map(entity(PortInstanceIdentifier), list(entity(Connection))),
            from_port_number_map: map(entity(Connection), i128),
            to_port_number_map: map(entity(Connection), i128),
            unconnected_port_set: list(entity(PortInstanceIdentifier)),
            connections: list(entity(ResolvedConnection)),
        }
        methods {
            component_instance_map -> list(tuple(rewrap(InterfaceInstance::Component), span)),
            unqualified_name -> str,
        }
    }

    entity TopologyPort native fpp_analysis::semantics::TopologyPort {
        fields {
            name: str,
            node_id: node,
            loc: span,
            pii: entity(PortInstanceIdentifier),
            underlying_loc: span,
        }
    }

    entity TransitionGraph native fpp_analysis::semantics::state_machine::TransitionGraph {
        fields {
            initial_node: opt(entity(TransitionGraphNode)),
            arc_map: map(entity(TransitionGraphNode), list(union(TransitionGraphArc))),
        }
        methods {
            get_reverse_graph -> entity(TransitionGraph),
        }
    }

    entity TransitionGraphNode native fpp_analysis::semantics::state_machine::transition_graph::Node {
        fields {
            soc: union(StateOrChoice),
        }
    }

    entity UseDefMatching native fpp_analysis::semantics::UseDefMatching {
        fields {
            node: node,
            qualified_name: entity(QualifiedName),
            symbol: symbol,
        }
    }

    leaf_enum Direction native fpp_analysis::semantics::Direction {
        Input: unit,
        Output: unit,
    }

    leaf_enum IntegerFormatKind native fpp_analysis::semantics::IntegerFormatKind {
        Character: unit,
        Decimal: unit,
        Hexadecimal: unit,
        Octal: unit,
    }

    leaf_enum Kind native fpp_analysis::semantics::state_machine::Kind {
        External: unit,
        Internal: unit,
    }

    leaf_enum RationalFormatKind native fpp_analysis::semantics::RationalFormatKind {
        Exponent: unit,
        Fixed: unit,
        General: unit,
    }

}
