//! Compile-time-expanded semantic-layer bindings.
//!
//! [`defs`] is the checked-in declaration file — a mechanical mirror of the
//! `fpp_analysis` semantic layer, generated by
//! `cargo run -p fpp_python --features bindgen --bin fpp_sem_bindgen`. The
//! `fpp_python_macros::fpp_sem_bindings!` invocation inside it expands, at
//! compile time, into the read-only wrappers for the semantic data structures
//! (`Symbol`/`Type`/`Value` + the entity layer), their union `*Ref` newtypes +
//! Python aliases, and the leaf-enum mirrors.
//!
//! [`defs_manual`] is the hand-authored companion declaration — the nested/thin
//! entity layer, the `PortInstance` closed union, and the top-level symbol-keyed
//! entities (`Component`/`ComponentInstance`/`Interface`/`Topology`/`System`/
//! `StateMachine`) — and [`hand`] holds the escape hatches (sibling `#[pymethods]`
//! blocks + the node-backed `State`) whose behavior the macro cannot produce
//! mechanically. All three re-export through `crate::sem::*` so callers reference
//! stable paths regardless of which layer owns a type.

mod defs;
mod defs_manual;
mod hand;

// `defs` (generated): the `Type`/`Value`/`Symbol`/`StateMachineElement` unions
// and their `*Ref`/`*_ref`/`build_*` items, plus `defs::register` /
// `defs::union_aliases` (shadowed by the combined wrappers below).
pub use defs::*;
pub use hand::{InstanceRef, build_type};
// Crate-internal escape-hatch helpers reached by generated code via
// `crate::sem::{build_spec, instance_ref}` (`pub(crate)`, so not `pub use`).
pub(crate) use hand::{build_spec, instance_ref};

// `defs_manual` (hand-authored): the nested/thin entity layer, the `PortInstance`
// closed union, and the top-level symbol-keyed entities. Re-exported by name so
// the combined `register`/`union_aliases` below don't clash with the globbed
// `defs::*` ones. (The `Special`/`Topology` port subclasses are registered inside
// `defs_manual`; they need no Rust re-export.)
pub use defs_manual::{
    Component, ComponentInstance, Connection, Endpoint, GeneralPortInstance, Interface,
    InternalPortInstance, PortInstance, PortInstanceRef, StateMachine, System, Topology,
    build_component, build_component_instance, build_interface, build_port_instance,
    build_state_machine, build_system, build_topology, port_instance_ref,
};
// The symbol-keyed `*_by_symbol` resolvers are crate-internal (used by the
// hand-written cross-layer escape hatches in `hand`).
pub(crate) use defs_manual::{
    component_by_symbol, component_instance_by_symbol, interface_by_symbol, topology_by_symbol,
};

/// Register every generated + hand-authored semantic pyclass with the module.
pub fn register(m: &::pyo3::Bound<'_, ::pyo3::types::PyModule>) -> ::pyo3::PyResult<()> {
    defs::register(m)?;
    defs_manual::register(m)?;
    hand::register(m)?;
    Ok(())
}

/// `(alias name, `Sub1 | Sub2 | …` RHS)` for every generated + hand-authored
/// closed union (`Type`/`Value`/`Symbol`/`StateMachineElement` + `PortInstance`).
pub fn union_aliases() -> ::std::vec::Vec<(&'static str, ::std::string::String)> {
    let mut aliases = defs::union_aliases();
    aliases.extend(defs_manual::union_aliases());
    aliases
}
