//! Compile-time-expanded semantic-layer bindings.
//!
//! [`defs`] is the checked-in declaration file — a mechanical 1:1 mirror of the
//! `fpp_analysis` semantic layer rooted at `Analysis`, generated by
//! `cargo run -p fpp_python --features bindgen --bin fpp_sem_bindgen`. The
//! `fpp_python_macros::fpp_sem_bindings!` invocation inside it expands, at
//! compile time, into the read-only PyO3 wrappers for the whole semantic graph:
//! the `Analysis` root, every closed union (`Symbol`/`Type`/`Value` + the
//! state-machine/port unions) with its `*Ref` newtype + Python alias, every
//! entity (including opaque handles), the payload structs, and the leaf-enum
//! mirrors — plus `defs::register` and `defs::union_aliases`.
//!
//! [`hand`] holds the single irreducible escape hatch the macro cannot produce
//! mechanically: `build_type` (the `Type` union is `custom_build` because an
//! "unknown" type whose def node is absent from the walk must render as the bare
//! base) and `Type`'s `__repr__`. It re-exports through `crate::sem::*` so callers
//! reference stable paths.

mod defs;
mod hand;

// `defs` (generated): the `Analysis` root, every union + its `*Ref`/`*_ref`/`build_*`
// items, the entities + `build_*`, payloads, leaf enums, and `defs::register` /
// `defs::union_aliases` (shadowed by the combined wrappers below).
pub use defs::*;
// The single surviving hand-build: the `Type` union is `custom_build`, so the
// generated `type_ref` calls `crate::sem::build_type`.
pub use hand::build_type;

/// Register every generated + hand-authored semantic pyclass with the module.
pub fn register(m: &::pyo3::Bound<'_, ::pyo3::types::PyModule>) -> ::pyo3::PyResult<()> {
    defs::register(m)?;
    hand::register(m)?;
    Ok(())
}

/// `(alias name, `Sub1 | Sub2 | …` RHS)` for every generated closed union.
pub fn union_aliases() -> ::std::vec::Vec<(&'static str, ::std::string::String)> {
    defs::union_aliases()
}
