# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

class AbsType(Type):
    @property
    def default_value(self) -> typing.Optional[Value]:
        r"""
        The declared default value, if any.
        """

class AbsTypeSymbol(Symbol):
    ...

class AbsTypeValue(Value):
    @property
    def type(self) -> typing.Optional[Type]:
        r"""
        The abstract type, if known.
        """

class AliasType(Type):
    @property
    def underlying(self) -> Type:
        r"""
        The underlying type, following alias chains.
        """

class AliasTypeSymbol(Symbol):
    ...

class AnonArrayType(Type):
    @property
    def array_size(self) -> typing.Optional[builtins.int]: ...
    @property
    def element_type(self) -> Type: ...

class AnonArrayValue(Value):
    @property
    def elements(self) -> builtins.list[Value]: ...

class AnonStructType(Type):
    @property
    def members(self) -> builtins.dict[builtins.str, Type]: ...

class AnonStructValue(Value):
    @property
    def members(self) -> builtins.dict[builtins.str, Value]: ...

class ArraySymbol(Symbol):
    ...

class ArrayType(Type):
    @property
    def array_size(self) -> typing.Optional[builtins.int]: ...
    @property
    def element_type(self) -> Type: ...
    @property
    def default(self) -> typing.Optional[Value]:
        r"""
        The declared default value, if any.
        """

class ArrayValue(Value):
    @property
    def elements(self) -> builtins.list[Value]: ...
    @property
    def type(self) -> typing.Optional[Type]:
        r"""
        The array type, if known.
        """

class AstNode:
    r"""
    Base class for every AST-node wrapper: holds the `Model` handle + the
    node, and the getters common to all nodes. Node wrappers are
    `#[pyclass(extends = AstNode)]` unit subclasses.
    """
    @property
    def node_id(self) -> builtins.int: ...
    @property
    def location(self) -> typing.Optional[Loc]: ...
    @property
    def pre_annotation(self) -> builtins.list[builtins.str]: ...
    @property
    def post_annotation(self) -> builtins.list[builtins.str]: ...
    @property
    def definition(self) -> typing.Optional[Symbol]:
        r"""
        The definition this use-site node resolves to (or None).
        """
    @property
    def resolved_type(self) -> typing.Optional[Type]:
        r"""
        The resolved type of this node (or None).
        """
    @property
    def resolved_value(self) -> typing.Optional[Value]:
        r"""
        The resolved (constant-folded) value of this node (or None).
        """

class BooleanType(Type):
    ...

class BooleanValue(Value):
    @property
    def value(self) -> builtins.bool: ...

class Command:
    @property
    def opcode(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def kind(self) -> typing.Optional[builtins.str]:
        r"""
        "Async" | "Guarded" | "Sync", or None for a synthesized param set/save command.
        """
    @property
    def priority(self) -> typing.Optional[builtins.int]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def spec(self) -> typing.Optional[SpecCommand]:
        r"""
        The `SpecCommand` AST node (formal params, opcode expr, annotations).
        """
    def __repr__(self) -> builtins.str: ...

class Component:
    @property
    def loc(self) -> typing.Optional[Loc]:
        r"""
        The source location of the definition.
        """
    @property
    def symbol(self) -> Symbol:
        r"""
        The symbol that names this entity.
        """
    @property
    def definition(self) -> DefComponent:
        r"""
        The defining AST node.
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def kind(self) -> builtins.str:
        r"""
        "active" | "passive" | "queued".
        """
    @property
    def port_interface(self) -> PortInterface: ...
    @property
    def commands(self) -> builtins.list[Command]:
        r"""
        The commands, ordered by opcode.
        """
    @property
    def telemetry(self) -> builtins.list[TlmChannel]:
        r"""
        The telemetry channels, ordered by id.
        """
    @property
    def events(self) -> builtins.list[Event]:
        r"""
        The events, ordered by id.
        """
    @property
    def params(self) -> builtins.list[Param]:
        r"""
        The parameters, ordered by id.
        """
    @property
    def containers(self) -> builtins.list[Container]:
        r"""
        The data-product containers, ordered by id.
        """
    @property
    def records(self) -> builtins.list[Record]:
        r"""
        The data-product records, ordered by id.
        """
    @property
    def state_machine_instances(self) -> builtins.list[StateMachineInstance]:
        r"""
        The state-machine instances, ordered by name.
        """
    @property
    def port_matchings(self) -> builtins.list[PortMatching]:
        r"""
        The port-matching specifiers.
        """
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class ComponentInstance:
    @property
    def loc(self) -> typing.Optional[Loc]:
        r"""
        The source location of the definition.
        """
    @property
    def symbol(self) -> Symbol:
        r"""
        The symbol that names this entity.
        """
    @property
    def definition(self) -> DefComponentInstance:
        r"""
        The defining AST node.
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def base_id(self) -> builtins.int: ...
    @property
    def max_id(self) -> builtins.int: ...
    @property
    def queue_size(self) -> typing.Optional[builtins.int]:
        r"""
        Declared queue size (constant-folded), if any.
        """
    @property
    def stack_size(self) -> typing.Optional[builtins.int]:
        r"""
        Declared stack size (constant-folded), if any.
        """
    @property
    def priority(self) -> typing.Optional[builtins.int]:
        r"""
        Declared priority (constant-folded), if any.
        """
    @property
    def cpu(self) -> typing.Optional[builtins.int]:
        r"""
        Declared CPU affinity (constant-folded), if any.
        """
    @property
    def impl_type(self) -> typing.Optional[builtins.str]:
        r"""
        The C++ implementation type name, if given.
        """
    @property
    def file(self) -> typing.Optional[builtins.str]:
        r"""
        The header file, if given.
        """
    @property
    def component(self) -> typing.Optional[Component]:
        r"""
        The component this is an instance of.
        """
    @property
    def init_specifiers(self) -> builtins.list[InitSpecifier]:
        r"""
        The init specifiers, ordered by phase.
        """
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class ComponentInstanceSymbol(Symbol):
    ...

class ComponentSymbol(Symbol):
    ...

class Connection:
    @property
    def graph_name(self) -> builtins.str: ...
    @property
    def from_(self) -> Endpoint:
        r"""
        The output (source) endpoint. Named `from_` because `from` is a Python
        keyword; `source` is an alias.
        """
    @property
    def source(self) -> Endpoint: ...
    @property
    def to(self) -> Endpoint:
        r"""
        The input (destination) endpoint.
        """
    @property
    def target(self) -> Endpoint: ...
    @property
    def is_unmatched(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ConstantSymbol(Symbol):
    ...

class Container:
    @property
    def id(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def spec(self) -> typing.Optional[SpecContainer]:
        r"""
        The `SpecContainer` AST node (default priority, annotations).
        """
    def __repr__(self) -> builtins.str: ...

class DefAbsType(AstNode):
    @property
    def name(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class DefAction(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

class DefAliasType(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class DefArray(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def size(self) -> Expr: ...
    @property
    def elt_type(self) -> TypeName: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def format(self) -> typing.Optional[builtins.str]: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class DefChoice(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def guard(self) -> Ident: ...
    @property
    def if_transition(self) -> TransitionExpr: ...
    @property
    def else_transition(self) -> TransitionExpr: ...
    def __repr__(self) -> builtins.str: ...

class DefComponent(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[DefAbsType | DefAliasType | DefArray | DefConstant | DefEnum | DefStateMachine | DefStruct | SpecCommand | SpecContainer | SpecEvent | SpecGeneralPortInstance | SpecInclude | SpecInterfaceImport | SpecInternalPort | SpecParam | SpecPortMatching | SpecRecord | SpecSpecialPortInstance | SpecStateMachineInstance | SpecTlmChannel]: ...
    def __repr__(self) -> builtins.str: ...

class DefComponentInstance(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def component(self) -> Ident | Qualified: ...
    @property
    def base_id(self) -> typing.Optional[Expr]: ...
    @property
    def impl_type(self) -> typing.Optional[builtins.str]: ...
    @property
    def file(self) -> typing.Optional[builtins.str]: ...
    @property
    def queue_size(self) -> typing.Optional[Expr]: ...
    @property
    def stack_size(self) -> typing.Optional[Expr]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def cpu(self) -> typing.Optional[Expr]: ...
    @property
    def init_specs(self) -> builtins.list[SpecInit]: ...
    def __repr__(self) -> builtins.str: ...

class DefConstant(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def value(self) -> Expr: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class DefEnum(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    @property
    def constants(self) -> builtins.list[DefEnumConstant]: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class DefEnumConstant(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def value(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

class DefGuard(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

class DefInterface(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[SpecGeneralPortInstance | SpecInterfaceImport | SpecSpecialPortInstance]: ...
    def __repr__(self) -> builtins.str: ...

class DefModule(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[DefAbsType | DefAliasType | DefArray | DefComponent | DefComponentInstance | DefConstant | DefEnum | DefInterface | DefModule | DefPort | DefStateMachine | DefStruct | DefSystem | DefTopology | SpecInclude | SpecLoc]: ...
    def __repr__(self) -> builtins.str: ...

class DefPort(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def return_type(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

class DefSignal(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

class DefState(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[DefChoice | DefState | SpecInclude | SpecInitialTransition | SpecStateEntry | SpecStateExit | SpecStateTransition]: ...
    def __repr__(self) -> builtins.str: ...

class DefStateMachine(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> typing.Optional[builtins.list[DefAbsType | DefAction | DefAliasType | DefArray | DefChoice | DefConstant | DefEnum | DefGuard | DefSignal | DefState | DefStruct | SpecInclude | SpecInitialTransition]]: ...
    def __repr__(self) -> builtins.str: ...

class DefStruct(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[StructTypeMember]: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class DefSystem(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def topology(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

class DefTopology(AstNode):
    @property
    def is_deployment(self) -> builtins.bool: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[SpecDirectConnectionGraph | SpecInclude | SpecInstance | SpecPatternConnectionGraph | SpecTlmPacketSet | SpecTopPort]: ...
    @property
    def implements(self) -> builtins.list[Ident | Qualified]: ...
    def __repr__(self) -> builtins.str: ...

class Diagnostic:
    r"""
    A diagnostic surfaced to Python.
    """
    @property
    def level(self) -> builtins.str: ...
    @property
    def message(self) -> builtins.str: ...
    @property
    def location(self) -> typing.Optional[Loc]: ...
    def __repr__(self) -> builtins.str: ...

class DoExpr(AstNode):
    @property
    def actions(self) -> builtins.list[Ident]: ...
    def __repr__(self) -> builtins.str: ...

class Endpoint:
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def port(self) -> PortInstanceIdentifier: ...
    @property
    def port_number(self) -> typing.Optional[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...

class EnumConstantSymbol(Symbol):
    ...

class EnumConstantValue(Value):
    @property
    def name(self) -> builtins.str:
        r"""
        The enum-constant member name.
        """
    @property
    def value(self) -> builtins.int: ...
    @property
    def type(self) -> Type:
        r"""
        The enum type.
        """

class EnumSymbol(Symbol):
    ...

class EnumType(Type):
    @property
    def rep_type(self) -> builtins.str:
        r"""
        Integer representation kind, e.g. "I32".
        """
    @property
    def signed(self) -> builtins.bool: ...
    @property
    def bits(self) -> builtins.int: ...
    @property
    def default(self) -> typing.Optional[Value]:
        r"""
        The declared default value, if any. (Enum constants are reachable via
        `.definition`, the `DefEnum` AST node.)
        """

class Event:
    @property
    def id(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def severity(self) -> typing.Optional[builtins.str]:
        r"""
        Event severity (e.g. "ActivityHigh", "Fatal"), from the AST spec.
        """
    @property
    def format(self) -> typing.Optional[builtins.str]:
        r"""
        The event format string, from the AST spec.
        """
    @property
    def spec(self) -> typing.Optional[SpecEvent]:
        r"""
        The `SpecEvent` AST node (params, throttle, annotations).
        """
    def __repr__(self) -> builtins.str: ...

class EventThrottle(AstNode):
    @property
    def count(self) -> Expr: ...
    @property
    def every(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

class Expr(AstNode):
    @property
    def kind(self) -> ExprArray | ExprArraySubscript | ExprBinop | ExprDot | ExprIdent | ExprLiteralBool | ExprLiteralInt | ExprLiteralFloat | ExprLiteralString | ExprParen | ExprSizeOf | ExprStruct | ExprUnop: ...
    def __repr__(self) -> builtins.str: ...

class ExprArray:
    @property
    def elements(self) -> builtins.list[Expr]: ...

class ExprArraySubscript:
    @property
    def e1(self) -> Expr: ...
    @property
    def e2(self) -> Expr: ...

class ExprBinop:
    @property
    def op(self) -> builtins.str: ...
    @property
    def left(self) -> Expr: ...
    @property
    def right(self) -> Expr: ...

class ExprDot:
    @property
    def e(self) -> Expr: ...
    @property
    def id(self) -> Ident: ...

class ExprIdent:
    @property
    def value(self) -> builtins.str: ...

class ExprLiteralBool:
    @property
    def value(self) -> builtins.bool: ...

class ExprLiteralFloat:
    @property
    def value(self) -> builtins.str: ...

class ExprLiteralInt:
    @property
    def value(self) -> builtins.str: ...

class ExprLiteralString:
    @property
    def value(self) -> builtins.str: ...

class ExprParen:
    @property
    def value(self) -> Expr: ...

class ExprSizeOf:
    @property
    def value(self) -> TypeName: ...

class ExprStruct:
    @property
    def elements(self) -> builtins.list[StructExprMember]: ...

class ExprUnop:
    @property
    def op(self) -> builtins.str: ...
    @property
    def e(self) -> Expr: ...

class FloatType(Type):
    @property
    def rep_type(self) -> builtins.str:
        r"""
        Float representation kind, e.g. "F32".
        """
    @property
    def bits(self) -> builtins.int: ...

class FloatValue(Value):
    @property
    def value(self) -> builtins.float: ...
    @property
    def rep_type(self) -> builtins.str:
        r"""
        Float representation kind, e.g. "F32".
        """

class FormalParam(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    def __repr__(self) -> builtins.str: ...

class GeneralPortInstance(PortInstance):
    @property
    def kind(self) -> typing.Optional[builtins.str]:
        r"""
        General port kind ("AsyncInput"/"GuardedInput"/"Output"/"SyncInput").
        """
    @property
    def priority(self) -> typing.Optional[builtins.int]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...
    @property
    def is_serial(self) -> builtins.bool: ...
    @property
    def type_symbol(self) -> typing.Optional[Symbol]:
        r"""
        The port-definition symbol for a typed port, else None (serial).
        """

class Ident(AstNode):
    @property
    def data(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class InitSpecifier:
    @property
    def phase(self) -> builtins.int: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    def __repr__(self) -> builtins.str: ...

class IntegerType(Type):
    ...

class IntegerValue(Value):
    @property
    def value(self) -> builtins.int: ...

class Interface:
    @property
    def loc(self) -> typing.Optional[Loc]:
        r"""
        The source location of the definition.
        """
    @property
    def symbol(self) -> Symbol:
        r"""
        The symbol that names this entity.
        """
    @property
    def definition(self) -> DefInterface:
        r"""
        The defining AST node.
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def port_interface(self) -> PortInterface: ...
    @property
    def imports(self) -> builtins.list[Interface]:
        r"""
        Imported interfaces.
        """
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class InterfaceSymbol(Symbol):
    ...

class InternalPortInstance(PortInstance):
    @property
    def input_kind(self) -> typing.Optional[builtins.str]: ...
    @property
    def priority(self) -> typing.Optional[builtins.int]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...

class LitString(AstNode):
    @property
    def data(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class Loc:
    r"""
    A resolved source location (0-indexed line/column, matching `fpp_core`).
    """
    @property
    def uri(self) -> builtins.str: ...
    @property
    def line(self) -> builtins.int: ...
    @property
    def column(self) -> builtins.int: ...
    @property
    def end_line(self) -> builtins.int: ...
    @property
    def end_column(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class Model:
    @property
    def has_errors(self) -> builtins.bool: ...
    @property
    def error_count(self) -> builtins.int: ...
    @property
    def diagnostics(self) -> builtins.list[Diagnostic]:
        r"""
        The diagnostics (errors, warnings, notes) emitted during analysis.
        """
    def ast(self) -> builtins.list[AstNode]:
        r"""
        The translation-unit top-level members.
        """
    def lookup(self, qualified_name:builtins.str) -> typing.Optional[Symbol]:
        r"""
        Look up a symbol by its fully-qualified (dotted) name.
        """
    def components(self) -> builtins.list[Component]:
        r"""
        All components in the model.
        """
    def component_instances(self) -> builtins.list[ComponentInstance]:
        r"""
        All component instances in the model.
        """
    def interfaces(self) -> builtins.list[Interface]:
        r"""
        All interfaces in the model.
        """
    def topologies(self) -> builtins.list[Topology]:
        r"""
        All topologies in the model.
        """
    def systems(self) -> builtins.list[System]:
        r"""
        All systems (deployments) in the model.
        """
    def state_machines(self) -> builtins.list[StateMachine]:
        r"""
        All state machines in the model.
        """
    def __repr__(self) -> builtins.str: ...

class ModuleSymbol(Symbol):
    ...

class Opaque(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class Param:
    @property
    def id(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def set_opcode(self) -> builtins.int: ...
    @property
    def save_opcode(self) -> builtins.int: ...
    @property
    def is_external(self) -> builtins.bool: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def type(self) -> typing.Optional[Type]:
        r"""
        The parameter's resolved type, from the AST spec.
        """
    @property
    def default(self) -> typing.Optional[Value]:
        r"""
        The parameter's default value, if any.
        """
    @property
    def spec(self) -> typing.Optional[SpecParam]: ...
    def __repr__(self) -> builtins.str: ...

class PortInstance:
    r"""
    A port instance. The concrete subclass reflects the variant
    (`GeneralPortInstance`, `SpecialPortInstance`, `InternalPortInstance`,
    `TopologyPortInstance`); the shared fields live on the base.
    """
    @property
    def variant(self) -> builtins.str:
        r"""
        "General" | "Special" | "Internal" | "Topology".
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def direction(self) -> typing.Optional[builtins.str]:
        r"""
        "Input" | "Output" | None.
        """
    @property
    def array_size(self) -> builtins.int: ...
    @property
    def is_async_input(self) -> builtins.bool:
        r"""
        Whether this port dispatches asynchronously.
        """
    @property
    def import_locs(self) -> builtins.list[Loc]:
        r"""
        Locations of the interface-import specs that pulled this port in.
        """
    def __repr__(self) -> builtins.str: ...

class PortInstanceIdentifier:
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def instance_name(self) -> builtins.str:
        r"""
        Fully-qualified name of the owning interface instance.
        """
    @property
    def port_name(self) -> builtins.str: ...
    @property
    def instance_kind(self) -> builtins.str:
        r"""
        "Component" | "Topology".
        """
    @property
    def port_instance(self) -> PortInstance: ...
    @property
    def instance(self) -> typing.Optional[ComponentInstance | Topology]:
        r"""
        The owning `ComponentInstance` (or `Topology` for topology instances).
        """
    def __repr__(self) -> builtins.str: ...

class PortInterface:
    @property
    def instance_type(self) -> builtins.str: ...
    @property
    def ports(self) -> builtins.list[PortInstance]: ...
    @property
    def special_ports(self) -> builtins.list[PortInstance]: ...
    def __repr__(self) -> builtins.str: ...

class PortMatching:
    @property
    def instance1(self) -> PortInstance: ...
    @property
    def instance2(self) -> PortInstance: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    def __repr__(self) -> builtins.str: ...

class PortSymbol(Symbol):
    ...

class PrimitiveIntType(Type):
    @property
    def rep_type(self) -> builtins.str:
        r"""
        Integer representation kind, e.g. "U32".
        """
    @property
    def signed(self) -> builtins.bool: ...
    @property
    def bits(self) -> builtins.int: ...

class PrimitiveIntegerValue(Value):
    @property
    def value(self) -> builtins.int: ...
    @property
    def rep_type(self) -> builtins.str:
        r"""
        Integer representation kind, e.g. "U32".
        """

class Qualified(AstNode):
    @property
    def qualifier(self) -> Ident | Qualified: ...
    @property
    def name(self) -> Ident: ...
    def __repr__(self) -> builtins.str: ...

class Record:
    @property
    def id(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def type(self) -> typing.Optional[Type]:
        r"""
        The record's resolved element type, from the AST spec.
        """
    @property
    def is_array(self) -> builtins.bool:
        r"""
        Whether the record is an array record.
        """
    @property
    def spec(self) -> typing.Optional[SpecRecord]: ...
    def __repr__(self) -> builtins.str: ...

class SpecCommand(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def opcode(self) -> typing.Optional[Expr]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

class SpecContainer(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def default_priority(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

class SpecDirectConnectionGraph(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def connections(self) -> builtins.list[AstNode]: ...
    def __repr__(self) -> builtins.str: ...

class SpecEvent(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def severity(self) -> builtins.str: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def format(self) -> builtins.str: ...
    @property
    def throttle(self) -> typing.Optional[EventThrottle]: ...
    def __repr__(self) -> builtins.str: ...

class SpecGeneralPortInstance(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def size(self) -> typing.Optional[Expr]: ...
    @property
    def port(self) -> typing.Optional[Ident | Qualified]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

class SpecInclude(AstNode):
    @property
    def file(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class SpecInit(AstNode):
    @property
    def phase(self) -> Expr: ...
    @property
    def code(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class SpecInitialTransition(AstNode):
    @property
    def transition(self) -> TransitionExpr: ...
    def __repr__(self) -> builtins.str: ...

class SpecInstance(AstNode):
    @property
    def instance(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

class SpecInterfaceImport(AstNode):
    @property
    def interface(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

class SpecInternalPort(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

class SpecLoc(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    @property
    def symbol(self) -> Ident | Qualified: ...
    @property
    def file(self) -> builtins.str: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class SpecParam(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def set_opcode(self) -> typing.Optional[Expr]: ...
    @property
    def save_opcode(self) -> typing.Optional[Expr]: ...
    @property
    def is_external(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class SpecPatternConnectionGraph(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    @property
    def source(self) -> Ident | Qualified: ...
    @property
    def targets(self) -> builtins.list[Ident | Qualified]: ...
    def __repr__(self) -> builtins.str: ...

class SpecPortMatching(AstNode):
    @property
    def port1(self) -> Ident: ...
    @property
    def port2(self) -> Ident: ...
    def __repr__(self) -> builtins.str: ...

class SpecRecord(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def record_type(self) -> TypeName: ...
    @property
    def is_array(self) -> builtins.bool: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

class SpecSpecialPortInstance(AstNode):
    @property
    def input_kind(self) -> typing.Optional[builtins.str]: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

class SpecStateEntry(AstNode):
    @property
    def actions(self) -> DoExpr: ...
    def __repr__(self) -> builtins.str: ...

class SpecStateExit(AstNode):
    @property
    def actions(self) -> DoExpr: ...
    def __repr__(self) -> builtins.str: ...

class SpecStateMachineInstance(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def state_machine(self) -> Ident | Qualified: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

class SpecStateTransition(AstNode):
    @property
    def signal(self) -> Ident: ...
    @property
    def guard(self) -> typing.Optional[Ident]: ...
    @property
    def transition_or_do(self) -> TransitionOrDoTransition | TransitionOrDoDo: ...
    def __repr__(self) -> builtins.str: ...

class SpecTlmChannel(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def update(self) -> typing.Optional[builtins.str]: ...
    @property
    def format(self) -> typing.Optional[builtins.str]: ...
    @property
    def low(self) -> builtins.list[TlmChannelLimit]: ...
    @property
    def high(self) -> builtins.list[TlmChannelLimit]: ...
    def __repr__(self) -> builtins.str: ...

class SpecTlmPacket(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def group(self) -> Expr: ...
    @property
    def members(self) -> builtins.list[SpecInclude | TlmChannelIdentifier]: ...
    def __repr__(self) -> builtins.str: ...

class SpecTlmPacketSet(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[SpecInclude | SpecTlmPacket]: ...
    @property
    def omitted(self) -> builtins.list[TlmChannelIdentifier]: ...
    def __repr__(self) -> builtins.str: ...

class SpecTopPort(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def underlying_port(self) -> AstNode: ...
    def __repr__(self) -> builtins.str: ...

class SpecialPortInstance(PortInstance):
    @property
    def special_kind(self) -> typing.Optional[builtins.str]:
        r"""
        Special port kind, FPP-style (e.g. "telemetry").
        """
    @property
    def priority(self) -> typing.Optional[builtins.int]: ...
    @property
    def queue_full(self) -> typing.Optional[builtins.str]: ...

class State:
    r"""
    A state of a state machine (may nest substates).
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def definition(self) -> DefState:
        r"""
        The defining `DefState` AST node.
        """
    @property
    def entry_actions(self) -> builtins.list[builtins.str]:
        r"""
        Names of the entry actions, in order.
        """
    @property
    def exit_actions(self) -> builtins.list[builtins.str]:
        r"""
        Names of the exit actions, in order.
        """
    @property
    def substates(self) -> builtins.list[State]:
        r"""
        The nested substates.
        """
    @property
    def is_leaf(self) -> builtins.bool:
        r"""
        Whether this is a leaf state (no substates).
        """
    def __repr__(self) -> builtins.str: ...

class StateMachine:
    @property
    def loc(self) -> typing.Optional[Loc]:
        r"""
        The source location of the definition.
        """
    @property
    def symbol(self) -> Symbol:
        r"""
        The symbol that names this entity.
        """
    @property
    def definition(self) -> DefStateMachine:
        r"""
        The defining AST node.
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def kind(self) -> builtins.str:
        r"""
        "External" | "Internal".
        """
    @property
    def actions(self) -> builtins.list[StateMachineElement]:
        r"""
        The actions, as typed symbols.
        """
    @property
    def guards(self) -> builtins.list[StateMachineElement]:
        r"""
        The guards, as typed symbols.
        """
    @property
    def signals(self) -> builtins.list[StateMachineElement]:
        r"""
        The signals, as typed symbols.
        """
    @property
    def states(self) -> builtins.list[State]:
        r"""
        The top-level states (each may nest substates).
        """
    @property
    def leaf_states(self) -> builtins.list[builtins.str]:
        r"""
        The unqualified names of the leaf states.
        """
    @property
    def blocking_error(self) -> builtins.bool:
        r"""
        Whether a blocking analysis error was recorded for this state machine.
        """
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class StateMachineElement:
    r"""
    A definition inside a state machine: an action, guard, signal, state, or
    choice. Discriminate with `.kind`.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        "Action" | "Guard" | "Signal" | "State" | "Choice".
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def definition(self) -> AstNode:
        r"""
        The defining AST node.
        """
    @property
    def type(self) -> typing.Optional[Type]:
        r"""
        The declared payload type of an action/guard/signal, if any.
        """
    def __repr__(self) -> builtins.str: ...

class StateMachineInstance:
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def state_machine(self) -> typing.Optional[StateMachine]:
        r"""
        The state machine this is an instance of.
        """
    @property
    def spec(self) -> typing.Optional[SpecStateMachineInstance]: ...
    def __repr__(self) -> builtins.str: ...

class StateMachineSymbol(Symbol):
    ...

class StringType(Type):
    @property
    def size(self) -> typing.Optional[builtins.int]:
        r"""
        String size, if bounded.
        """

class StringValue(Value):
    @property
    def value(self) -> builtins.str: ...

class StructExprMember(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def value(self) -> Expr: ...
    def __repr__(self) -> builtins.str: ...

class StructSymbol(Symbol):
    ...

class StructType(Type):
    @property
    def members(self) -> builtins.dict[builtins.str, Type]: ...
    @property
    def default(self) -> typing.Optional[Value]:
        r"""
        The declared default value, if any.
        """
    @property
    def member_sizes(self) -> builtins.dict[builtins.str, builtins.int]:
        r"""
        Per-member array multiplicity (member name -> size).
        """

class StructTypeMember(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def size(self) -> typing.Optional[Expr]: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def format(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

class StructValue(Value):
    @property
    def members(self) -> builtins.dict[builtins.str, Value]: ...
    @property
    def type(self) -> typing.Optional[Type]:
        r"""
        The struct type, if known.
        """

class Symbol:
    r"""
    A resolved symbol. The concrete subclass reflects the symbol's kind
    (`ComponentSymbol`, `PortSymbol`, ...); navigation and identity live here.
    """
    @property
    def kind(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def node_id(self) -> builtins.int: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    @property
    def definition(self) -> AstNode:
        r"""
        The defining AST node wrapper.
        """
    @property
    def parent(self) -> typing.Optional[Symbol]: ...
    def as_component(self) -> typing.Optional[Component]:
        r"""
        The `Component` entity this symbol defines, or None.
        """
    def as_component_instance(self) -> typing.Optional[ComponentInstance]:
        r"""
        The `ComponentInstance` entity this symbol defines, or None.
        """
    def as_interface(self) -> typing.Optional[Interface]:
        r"""
        The `Interface` entity this symbol defines, or None.
        """
    def as_topology(self) -> typing.Optional[Topology]:
        r"""
        The `Topology` entity this symbol defines, or None.
        """
    def as_system(self) -> typing.Optional[System]:
        r"""
        The `System` entity this symbol defines, or None.
        """
    def as_state_machine(self) -> typing.Optional[StateMachine]:
        r"""
        The `StateMachine` entity this symbol defines, or None.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...

class System:
    @property
    def loc(self) -> typing.Optional[Loc]:
        r"""
        The source location of the definition.
        """
    @property
    def symbol(self) -> Symbol:
        r"""
        The symbol that names this entity.
        """
    @property
    def definition(self) -> DefSystem:
        r"""
        The defining AST node.
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def topology(self) -> typing.Optional[Topology]:
        r"""
        The deployment topology named by this system.
        """
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class SystemSymbol(Symbol):
    ...

class TlmChannel:
    @property
    def id(self) -> builtins.int: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def loc(self) -> typing.Optional[Loc]: ...
    @property
    def type(self) -> typing.Optional[Type]:
        r"""
        The channel's resolved type, from the AST spec.
        """
    @property
    def format(self) -> typing.Optional[builtins.str]:
        r"""
        The channel's format string, if specified.
        """
    @property
    def spec(self) -> typing.Optional[SpecTlmChannel]:
        r"""
        The `SpecTlmChannel` AST node (limits, update kind, annotations).
        """
    def __repr__(self) -> builtins.str: ...

class TlmChannelIdentifier(AstNode):
    @property
    def component_instance(self) -> Ident | Qualified: ...
    @property
    def channel_name(self) -> Ident: ...
    def __repr__(self) -> builtins.str: ...

class TlmChannelLimit(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    @property
    def value(self) -> Expr: ...
    def __repr__(self) -> builtins.str: ...

class Topology:
    @property
    def loc(self) -> typing.Optional[Loc]:
        r"""
        The source location of the definition.
        """
    @property
    def symbol(self) -> Symbol:
        r"""
        The symbol that names this entity.
        """
    @property
    def definition(self) -> DefTopology:
        r"""
        The defining AST node.
        """
    @property
    def name(self) -> builtins.str: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def instances(self) -> builtins.list[ComponentInstance]:
        r"""
        The component instances declared in this topology (resolved).
        """
    @property
    def implements(self) -> builtins.list[Interface]:
        r"""
        The interfaces this topology implements (resolved).
        """
    @property
    def unconnected_ports(self) -> builtins.list[PortInstanceIdentifier]:
        r"""
        Ports with a direction that have no connections in this topology.
        """
    @property
    def port_interface(self) -> PortInterface:
        r"""
        The topology-level port interface (its exported top-level ports).
        """
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def connections(self) -> builtins.list[Connection]:
        r"""
        The connections of this topology (across all connection graphs).
        """
    def __repr__(self) -> builtins.str: ...

class TopologyPortInstance(PortInstance):
    @property
    def underlying(self) -> typing.Optional[PortInstance]:
        r"""
        The underlying aliased port instance.
        """

class TopologySymbol(Symbol):
    ...

class TransitionExpr(AstNode):
    @property
    def actions(self) -> typing.Optional[DoExpr]: ...
    @property
    def target(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

class TransitionOrDoDo:
    @property
    def value(self) -> DoExpr: ...

class TransitionOrDoTransition:
    @property
    def value(self) -> TransitionExpr: ...

class Type:
    r"""
    A structurally-interned type. The concrete subclass reflects the type's
    shape (`ArrayType`, `EnumType`, ...); `.kind`, the `is_*` predicates,
    `.definition` and identity live on the base.
    """
    @property
    def kind(self) -> builtins.str: ...
    @property
    def is_int(self) -> builtins.bool: ...
    @property
    def is_float(self) -> builtins.bool: ...
    @property
    def is_numeric(self) -> builtins.bool: ...
    @property
    def is_bool(self) -> builtins.bool: ...
    @property
    def is_string(self) -> builtins.bool: ...
    @property
    def is_primitive(self) -> builtins.bool: ...
    @property
    def is_enum(self) -> builtins.bool: ...
    @property
    def is_array(self) -> builtins.bool: ...
    @property
    def is_struct(self) -> builtins.bool: ...
    @property
    def is_abs_type(self) -> builtins.bool: ...
    @property
    def is_alias(self) -> builtins.bool: ...
    @property
    def is_displayable(self) -> builtins.bool: ...
    @property
    def definition(self) -> typing.Optional[AstNode]:
        r"""
        The defining AST node (for named types), else None.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other:typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...

class TypeName(AstNode):
    @property
    def kind(self) -> TypeNameBool | TypeNameFloating | TypeNameInteger | TypeNameQualIdent | TypeNameString: ...
    def __repr__(self) -> builtins.str: ...

class TypeNameBool:
    ...

class TypeNameFloating:
    @property
    def value(self) -> builtins.str: ...

class TypeNameInteger:
    @property
    def value(self) -> builtins.str: ...

class TypeNameQualIdent:
    @property
    def value(self) -> Ident | Qualified: ...

class TypeNameString:
    @property
    def value(self) -> typing.Optional[Expr]: ...

class Value:
    r"""
    A resolved (constant-folded) value. The concrete subclass reflects the value
    kind (`IntegerValue`, `ArrayValue`, ...); `.kind` lives on the base.
    """
    @property
    def kind(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

def analyze(source:builtins.str, uri:builtins.str='<string>') -> Model:
    r"""
    Analyze FPP source text and return a [`Model`].
    """

