// @generated by fpp_bindgen from fpp_ast v0.0.0 — do not edit
//! Declarative mirror of the `fpp_ast` grammar, expanded by the
//! `fpp_python_macros::fpp_ast_bindings!` proc macro into the PyO3 AST-node
//! wrappers + the recording walk. GENERATED by `fpp_bindgen` — do not edit
//! by hand; regenerate with
//! `cargo run -p fpp_python --features bindgen --bin fpp_bindgen`.
#![allow(dead_code, unused_variables, clippy::all)]

fpp_python_macros::fpp_ast_bindings! {
    leaves {
        Binop,
        ComponentKind,
        ConnectionPatternKind,
        EventSeverity,
        FloatKind,
        FormalParamKind,
        GeneralPortInstanceKind,
        InputPortKind,
        IntegerKind,
        QueueFull,
        SpecLocKind,
        SpecialPortInstanceKind,
        TlmChannelLimitKind,
        TlmChannelUpdate,
        Unop,
    }

    shadowed { Connection, PortInstanceIdentifier }

    node Connection {
        is_unmatched: bool,
        from_port: PortInstanceIdentifier,
        from_index: Expr?,
        to_port: PortInstanceIdentifier,
        to_index: Expr?,
    }

    node DefAbsType {
        name: Name,
    }

    node DefAction {
        name: Name,
        type_name: TypeName?,
    }

    node DefAliasType {
        name: Name,
        type_name: TypeName,
        is_dictionary_def: bool,
    }

    node DefArray {
        name: Name,
        size: Expr,
        elt_type: TypeName,
        default: Expr?,
        format: LitString?,
        is_dictionary_def: bool,
    }

    node DefChoice {
        name: Name,
        guard: Ident,
        if_transition: TransitionExpr,
        else_transition: TransitionExpr,
    }

    node DefComponent {
        kind: ComponentKind,
        name: Name,
        members: [ComponentMember],
    }

    node DefComponentInstance {
        name: Name,
        component: QualIdent,
        base_id: Expr?,
        impl_type: LitString?,
        file: LitString?,
        queue_size: Expr?,
        stack_size: Expr?,
        priority: Expr?,
        cpu: Expr?,
        init_specs: [SpecInit],
    }

    node DefConstant {
        name: Name,
        value: Expr,
        is_dictionary_def: bool,
    }

    node DefEnum {
        name: Name,
        type_name: TypeName?,
        constants: [DefEnumConstant],
        default: Expr?,
        is_dictionary_def: bool,
    }

    node DefEnumConstant {
        name: Name,
        value: Expr?,
    }

    node DefGuard {
        name: Name,
        type_name: TypeName?,
    }

    node DefInterface {
        name: Name,
        members: [InterfaceMember],
    }

    node DefModule {
        name: Name,
        members: [ModuleMember],
    }

    node DefPort {
        name: Name,
        params: [FormalParam],
        return_type: TypeName?,
    }

    node DefSignal {
        name: Name,
        type_name: TypeName?,
    }

    node DefState {
        name: Name,
        members: [StateMember],
    }

    node DefStateMachine {
        name: Name,
        members: [StateMachineMember]?,
    }

    node DefStruct {
        name: Name,
        members: [StructTypeMember],
        default: Expr?,
        is_dictionary_def: bool,
    }

    node DefSystem {
        name: Name,
        topology: QualIdent,
    }

    node DefTopology {
        is_deployment: bool,
        name: Name,
        members: [TopologyMember],
        implements: [QualIdent],
    }

    node DoExpr {
        actions: [Ident],
    }

    node EventThrottle {
        count: Expr,
        every: Expr?,
    }

    node Expr {
        kind: ExprKind,
    }

    node FormalParam {
        kind: FormalParamKind,
        name: Name,
        type_name: TypeName,
    }

    node Ident {
        data: String,
    }

    node LitString {
        data: String,
    }

    node PortInstanceIdentifier {
        interface_instance: QualIdent,
        port_name: Ident,
    }

    node Qualified {
        qualifier: QualIdent,
        name: Ident,
    }

    node SpecCommand {
        kind: InputPortKind,
        name: Name,
        params: [FormalParam],
        opcode: Expr?,
        priority: Expr?,
        queue_full: QueueFull?,
    }

    node SpecContainer {
        name: Name,
        id: Expr?,
        default_priority: Expr?,
    }

    node SpecDirectConnectionGraph {
        name: Name,
        connections: [Connection],
    }

    node SpecEvent {
        name: Name,
        params: [FormalParam],
        severity: EventSeverity,
        id: Expr?,
        format: LitString,
        throttle: EventThrottle?,
    }

    node SpecGeneralPortInstance {
        kind: GeneralPortInstanceKind,
        name: Name,
        size: Expr?,
        port: QualIdent?,
        priority: Expr?,
        queue_full: QueueFull?,
    }

    node SpecInclude {
        file: LitString,
    }

    node SpecInit {
        phase: Expr,
        code: LitString,
    }

    node SpecInitialTransition {
        transition: TransitionExpr,
    }

    node SpecInstance {
        instance: QualIdent,
    }

    node SpecInterfaceImport {
        interface: QualIdent,
    }

    node SpecInternalPort {
        name: Name,
        params: [FormalParam],
        priority: Expr?,
        queue_full: QueueFull?,
    }

    node SpecLoc {
        kind: SpecLocKind,
        symbol: QualIdent,
        file: LitString,
        is_dictionary_def: bool,
    }

    node SpecParam {
        name: Name,
        type_name: TypeName,
        default: Expr?,
        id: Expr?,
        set_opcode: Expr?,
        save_opcode: Expr?,
        is_external: bool,
    }

    node SpecPatternConnectionGraph {
        kind: ConnectionPatternKind,
        source: QualIdent,
        targets: [QualIdent],
    }

    node SpecPortMatching {
        port1: Ident,
        port2: Ident,
    }

    node SpecRecord {
        name: Name,
        record_type: TypeName,
        is_array: bool,
        id: Expr?,
    }

    node SpecSpecialPortInstance {
        input_kind: InputPortKind?,
        kind: SpecialPortInstanceKind,
        name: Name,
        priority: Expr?,
        queue_full: QueueFull?,
    }

    node SpecStateEntry {
        actions: DoExpr,
    }

    node SpecStateExit {
        actions: DoExpr,
    }

    node SpecStateMachineInstance {
        name: Name,
        state_machine: QualIdent,
        priority: Expr?,
        queue_full: QueueFull?,
    }

    node SpecStateTransition {
        signal: Ident,
        guard: Ident?,
        transition_or_do: TransitionOrDo,
    }

    node SpecTlmChannel {
        name: Name,
        type_name: TypeName,
        id: Expr?,
        update: TlmChannelUpdate?,
        format: LitString?,
        low: [TlmChannelLimit],
        high: [TlmChannelLimit],
    }

    node SpecTlmPacket {
        name: Name,
        id: Expr?,
        group: Expr,
        members: [TlmPacketMember],
    }

    node SpecTlmPacketSet {
        name: Name,
        members: [TlmPacketSetMember],
        omitted: [TlmChannelIdentifier],
    }

    node SpecTopPort {
        name: Name,
        underlying_port: PortInstanceIdentifier,
    }

    node StructExprMember {
        name: Name,
        value: Expr,
    }

    node StructTypeMember {
        name: Name,
        size: Expr?,
        type_name: TypeName,
        format: LitString?,
    }

    node TlmChannelIdentifier {
        component_instance: QualIdent,
        channel_name: Ident,
    }

    node TlmChannelLimit {
        kind: TlmChannelLimitKind,
        value: Expr,
    }

    node TransitionExpr {
        actions: DoExpr?,
        target: QualIdent,
    }

    node TypeName {
        kind: TypeNameKind,
    }

    union ComponentMember {
        DefAbsType(DefAbsType),
        DefAliasType(DefAliasType),
        DefArray(DefArray),
        DefConstant(DefConstant),
        DefEnum(DefEnum),
        DefStateMachine(DefStateMachine),
        DefStruct(DefStruct),
        SpecCommand(SpecCommand),
        SpecContainer(SpecContainer),
        SpecEvent(SpecEvent),
        SpecInclude(SpecInclude),
        SpecInternalPort(SpecInternalPort),
        SpecParam(SpecParam),
        SpecPortInstance(SpecPortInstance),
        SpecPortMatching(SpecPortMatching),
        SpecRecord(SpecRecord),
        SpecStateMachineInstance(SpecStateMachineInstance),
        SpecTlmChannel(SpecTlmChannel),
        SpecInterfaceImport(SpecInterfaceImport),
    }

    union InterfaceMember {
        SpecPortInstance(SpecPortInstance),
        SpecInterfaceImport(SpecInterfaceImport),
    }

    union ModuleMember {
        DefAbsType(DefAbsType),
        DefAliasType(DefAliasType),
        DefArray(DefArray),
        DefComponent(DefComponent),
        DefComponentInstance(DefComponentInstance),
        DefConstant(DefConstant),
        DefEnum(DefEnum),
        DefInterface(DefInterface),
        DefModule(DefModule),
        DefPort(DefPort),
        DefStateMachine(DefStateMachine),
        DefStruct(DefStruct),
        DefSystem(DefSystem),
        DefTopology(DefTopology),
        SpecInclude(SpecInclude),
        SpecLoc(SpecLoc),
    }

    union QualIdent {
        Unqualified(Ident),
        Qualified(Qualified),
    }

    union SpecPortInstance {
        General(SpecGeneralPortInstance),
        Special(SpecSpecialPortInstance),
    }

    union StateMachineMember {
        DefAbsType(DefAbsType),
        DefAliasType(DefAliasType),
        DefArray(DefArray),
        DefAction(DefAction),
        DefChoice(DefChoice),
        DefConstant(DefConstant),
        DefEnum(DefEnum),
        DefGuard(DefGuard),
        DefSignal(DefSignal),
        DefState(DefState),
        DefStruct(DefStruct),
        SpecInclude(SpecInclude),
        SpecInitialTransition(SpecInitialTransition),
    }

    union StateMember {
        DefChoice(DefChoice),
        DefState(DefState),
        SpecInclude(SpecInclude),
        SpecInitialTransition(SpecInitialTransition),
        SpecStateEntry(SpecStateEntry),
        SpecStateExit(SpecStateExit),
        SpecStateTransition(SpecStateTransition),
    }

    union TlmPacketMember {
        SpecInclude(SpecInclude),
        TlmChannelIdentifier(TlmChannelIdentifier),
    }

    union TlmPacketSetMember {
        SpecInclude(SpecInclude),
        SpecTlmPacket(SpecTlmPacket),
    }

    union TopologyMember {
        SpecInstance(SpecInstance),
        SpecDirectConnectionGraph(SpecDirectConnectionGraph),
        SpecPatternConnectionGraph(SpecPatternConnectionGraph),
        SpecInclude(SpecInclude),
        SpecTopPort(SpecTopPort),
        SpecTlmPacketSet(SpecTlmPacketSet),
    }

    kind ExprKind {
        Array([Expr]),
        ArraySubscript { e1: Expr, e2: Expr },
        Binop { left: Expr, op: Binop, right: Expr },
        Dot { e: Expr, id: Ident },
        Ident(String),
        LiteralBool(bool),
        LiteralInt(String),
        LiteralFloat(String),
        LiteralString(String),
        Paren(Expr),
        SizeOf(TypeName),
        Struct([StructExprMember]),
        Unop { op: Unop, e: Expr },
    }

    kind TransitionOrDo {
        Transition(TransitionExpr),
        Do(DoExpr),
    }

    kind TypeNameKind {
        Bool,
        Floating(FloatKind),
        Integer(IntegerKind),
        QualIdent(QualIdent),
        String(Expr?),
    }

}
