//! Compile-time-expanded AST bindings.
//!
//! [`defs`] is the checked-in declaration file — a clean ~1:1 mirror of the
//! `fpp_ast` grammar, generated by `cargo run -p fpp_bindgen`. The
//! `fpp_python_macros::fpp_ast_bindings!` invocation inside it expands, at compile
//! time, into the `AstNode` base + one `#[pyclass(extends = AstNode)]` wrapper
//! per node, the kind/union `*Ref` newtypes, the `NodeKind` tag, and the
//! recording walk (`walk_trans_unit` + `walk_*`). Nothing here is tracked except
//! `defs.rs`; the expansion happens in the background.

mod defs;
pub use defs::*;
