[package]
name = "fpp_parser"
description = "Recursive descent AST parser for the FPP compiler"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fpp_lexer = { path = "../fpp_lexer", version = "=0.0.0" }
fpp_core = { path = "../fpp_core", version = "=0.0.0" }
fpp_ast = { path = "../fpp_ast", version = "=0.0.0" }
rustc-hash = "2.1.1"

[dev-dependencies]
fpp_errors = { path = "../fpp_errors" }
fpp_fs = { path = "../fpp_fs" }
pretty_assertions = "1.4.1"
