[package]
name = "fpp_lsp_server"
description = "Language Server Protocol implementation for the FPP language"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fpp_analysis = { path = "../fpp_analysis", version = "=0.0.0" }
fpp_ast = { path = "../fpp_ast", version = "=0.0.0" }
fpp_core = { path = "../fpp_core", version = "=0.0.0" }
fpp_parser = { path = "../fpp_parser", version = "=0.0.0" }
fpp_lsp_parser = { path = "../fpp_lsp_parser", version = "=0.0.0" }
fpp_format = { path = "../fpp_format", version = "=0.0.0" }

lsp-server = "=0.7.9"
serde_json = "1.0.145"
lsp-types = "0.97.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tracing = "0.1.41"
anyhow = "1.0.100"
crossbeam-channel = "0.5.15"
tracing-subscriber = { version =  "0.3.22", features = ["chrono", "env-filter"] }
url = "2"
ignore = "0.4"
clap = { version = "4.5.60", features = ["derive"] }

[dev-dependencies]
fpp_fs = { path = "../fpp_fs" }
fpp_errors = { path = "../fpp_errors" }
