package com.github.kronos3.fpp_rust

object SemanticTokenTypes {
    const val Module: String = "module"
    const val Topology: String = "topology"
    const val Component: String = "component"
    const val Interface: String = "interface"
    const val ComponentInstance: String = "componentInstance"
    const val Constant: String = "constant"
    const val EnumConstant: String = "enumConstant"
    const val StructMember: String = "structMember"
    const val GraphGroup: String = "graphGroup"
    const val PortInstance: String = "portInstance"
    const val Port: String = "port"
    const val AbstractType: String = "abstractType"
    const val AliasType: String = "aliasType"
    const val ArrayType: String = "arrayType"
    const val EnumType: String = "enumType"
    const val StructType: String = "structType"
    const val PrimitiveType: String = "primitiveType"
    const val FormalParameter: String = "formalParameter"
    const val Command: String = "command"
    const val Event: String = "event"
    const val Telemetry: String = "telemetry"
    const val Parameter: String = "parameter"
    const val DataProduct: String = "dataProduct"
    const val StateMachine: String = "stateMachine"
    const val StateMachineInstance: String = "stateMachineInstance"
    const val TelemetryPacketSet: String = "telemetryPacketSet"
    const val TelemetryPacket: String = "telemetryPacket"
    const val Action: String = "action"
    const val Guard: String = "guard"
    const val Signal: String = "signal"
    const val State: String = "state"
    const val Annotation: String = "annotation"
    const val Comment: String = "comment"
    const val Number: String = "number"
    const val String: String = "string"
    const val Keyword: String = "keyword"
}
