[package]
name = "fpp_analysis"
description = "Semantic analysis passes and type checking for the FPP compiler"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]

disabled-tests = []

[dependencies]
fpp_ast = { path = "../fpp_ast", version = "=0.0.0" }
fpp_core = { path = "../fpp_core", version = "=0.0.0" }
fpp_util = { path = "../fpp_util", version = "=0.0.0" }
fpp_macros = { path = "../fpp_macros", version = "=0.0.0" }
fpp_parser = { path = "../fpp_parser", version = "=0.0.0" }
rustc-hash = "2.1.1"

[dev-dependencies]
fpp_errors = { path = "../fpp_errors" }
fpp_fs = { path = "../fpp_fs" }
pretty_assertions = "1.4.1"
